# This file was generated by GoReleaser. DO NOT EDIT.
cask "incorpus" do
  version "0.35.0"

  on_macos do
    on_arm do
      sha256 "7bd95b3c4b2d03f6182b59ce79cc78805150fd359d51aa8ad4a511f426bf09ab"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa0d179102da2e6a1fe17846272bd358c089e7ca23b10c2b015d987fd1e85048"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a54a35704f41cc1932fc6afcb40ff67396d0ec0fd9119d39d8e5382e993cff0a"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f18799f918bae0f05fc3f66a0826c4b1d81591c32008363ec9ca9cb0847ac176"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "incorpus"
  desc "Agentic CLI for the Incorpus business management platform"
  homepage "https://incorpus.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "incorpus"

  # No zap stanza required
end
