# This file was generated by GoReleaser. DO NOT EDIT.
cask "incorpus" do
  version "0.32.0"

  on_macos do
    on_arm do
      sha256 "4a8f994bfdd8c2f919655a49b550d01444ff75024448352e70a238b5024b685b"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "a34eb75b294edd6c4563487ebd6e4dbd4fcc69150aaba5b018724caf31cc5bbf"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8b165120502f907622af9b71208d3465b6bd76e9f75d2937b58c7bad65fff34b"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ae0110a1549b51685c6d5547ec760d108e4e5ba31cca9cc8ec390258026aeabc"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "incorpus"
  desc "Agentic CLI for the Incorpus business management platform"
  homepage "https://incorpus.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "incorpus"

  # No zap stanza required
end
