# This file was generated by GoReleaser. DO NOT EDIT.
cask "incorpus" do
  version "0.34.0"

  on_macos do
    on_arm do
      sha256 "808a2850e6e6f600805235f6017a535829627a05206b1e897e72c1ac8d42971b"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c058ffa6ddd128d7272cbf808d5432053acc9bfcb9a855be707a1233a454fe4"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cfe9efdf803a22ba7d21cc88464cac728ca1ce404156a363fa2d9e7fcefc9403"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ddf1ab17278801850dac4f023707ca76abbfc930611f58671dab77f8b1eb923"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "incorpus"
  desc "Agentic CLI for the Incorpus business management platform"
  homepage "https://incorpus.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "incorpus"

  # No zap stanza required
end
